from __future__ import annotations

import asyncio

from agent_overlord.config import AppConfig, HostConfig
from agent_overlord.domain.workers import PaneObservation
from agent_overlord.transports.tmux import TmuxTransport, transport_for


# Tabs are supported by old and new tmux releases and survive system-SSH command
# transport. Field values generated by tmux do not contain literal tabs.
FIELD_SEPARATOR = "\t"
LIST_FIELDS = (
    "#{session_id}",
    "#{session_name}",
    "#{window_id}",
    "#{window_index}",
    "#{window_name}",
    "#{pane_id}",
    "#{pane_index}",
    "#{pane_title}",
    "#{pane_current_path}",
    "#{pane_current_command}",
    "#{pane_start_command}",
    "#{pane_pid}",
    "#{pane_dead}",
    "#{pane_active}",
    "#{pane_activity}",
    "#{pane_width}",
    "#{pane_height}",
)


def _integer(value: str) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


class TmuxDiscovery:
    def __init__(self, config: AppConfig) -> None:
        self.config = config
        self.transports: dict[str, TmuxTransport] = {
            host.name: transport_for(host) for host in config.hosts
        }
        # A large fleet may contain dozens of panes. Starting one tmux/SSH process
        # per pane at once can briefly starve the TUI's input loop.
        self._capture_limit = asyncio.Semaphore(8)

    async def discover_host(self, host: HostConfig) -> list[PaneObservation]:
        transport = self.transports[host.name]
        format_string = FIELD_SEPARATOR.join(LIST_FIELDS)
        output = await transport.run_tmux("list-panes", "-a", "-F", format_string)
        rows = [self._parse_row(host, line) for line in output.splitlines() if line]
        captures_and_processes = await asyncio.gather(
            *(self._capture(transport, row.pane_id) for row in rows),
            self._process_snapshot(transport),
            return_exceptions=True,
        )
        captures = captures_and_processes[:-1]
        process_snapshot = captures_and_processes[-1]
        for row, capture in zip(rows, captures, strict=True):
            if isinstance(capture, list):
                row.content = capture
        if isinstance(process_snapshot, dict):
            for row in rows:
                if row.pane_pid is not None:
                    row.descendant_commands = self._descendant_commands(
                        row.pane_pid, process_snapshot
                    )
        return rows

    @staticmethod
    async def _process_snapshot(
        transport: TmuxTransport,
    ) -> dict[int, list[tuple[int, str]]]:
        output = await transport.run_command("ps", "-eo", "pid=,ppid=,args=")
        children: dict[int, list[tuple[int, str]]] = {}
        for line in output.splitlines():
            fields = line.strip().split(None, 2)
            if len(fields) != 3:
                continue
            try:
                pid, parent_pid = int(fields[0]), int(fields[1])
            except ValueError:
                continue
            children.setdefault(parent_pid, []).append((pid, fields[2]))
        return children

    @staticmethod
    def _descendant_commands(
        pane_pid: int, children: dict[int, list[tuple[int, str]]]
    ) -> list[str]:
        commands: list[str] = []
        pending = [pane_pid]
        visited = {pane_pid}
        while pending:
            parent = pending.pop()
            for pid, command in children.get(parent, []):
                if pid in visited:
                    continue
                visited.add(pid)
                commands.append(command)
                pending.append(pid)
        return commands

    async def discover_all(
        self,
    ) -> tuple[dict[str, list[PaneObservation]], dict[str, str]]:
        results = await asyncio.gather(
            *(self.discover_host(host) for host in self.config.hosts),
            return_exceptions=True,
        )
        observations: dict[str, list[PaneObservation]] = {}
        errors: dict[str, str] = {}
        for host, result in zip(self.config.hosts, results, strict=True):
            if isinstance(result, Exception):
                errors[host.name] = str(result)
            else:
                observations[host.name] = result
        return observations, errors

    async def _capture(self, transport: TmuxTransport, pane_id: str) -> list[str]:
        async with self._capture_limit:
            output = await transport.run_tmux(
                "capture-pane",
                "-p",
                # Do not use -J here. Joining wrapped rows can turn structured
                # agent output into multi-megabyte logical lines and stall the UI.
                "-S",
                f"-{self.config.capture_lines}",
                "-t",
                pane_id,
            )
        # Pane rows should already be terminal-width bounded. Retain a defensive
        # cap for unusual tmux output so classification and persistence stay cheap.
        return [line[-4096:] for line in output.rstrip().splitlines()]

    @staticmethod
    def _parse_row(host: HostConfig, line: str) -> PaneObservation:
        fields = line.split(FIELD_SEPARATOR)
        if len(fields) != len(LIST_FIELDS):
            raise ValueError(
                f"unexpected tmux output from {host.name}: expected {len(LIST_FIELDS)} "
                f"fields, received {len(fields)}"
            )
        return PaneObservation(
            host=host.name,
            tmux_socket=host.tmux_socket,
            session_id=fields[0],
            session_name=fields[1],
            window_id=fields[2],
            window_index=_integer(fields[3]) or 0,
            window_name=fields[4],
            pane_id=fields[5],
            pane_index=_integer(fields[6]) or 0,
            pane_title=fields[7],
            current_path=fields[8],
            current_command=fields[9],
            start_command=fields[10],
            pane_pid=_integer(fields[11]),
            pane_dead=fields[12] == "1",
            pane_active=fields[13] == "1",
            pane_activity=_integer(fields[14]),
            width=_integer(fields[15]),
            height=_integer(fields[16]),
        )
